### PR TITLE
Updates All around:

### PR DESCRIPTION
**Pull request by SaintFenix**
Long time no see,

I'm back and updating everything I can get my hands on.

1. New Software in README-EN? UPDATED!
2. New Games Organization from README-EN UPDATED!
3. Adding yet new software?! UPDATED!

Seriously though, There are a lot of changes here, mostly in catching up the other languages to English, since I've not been on as much. I spread the new games organization out to the other branches, and added two new softwares. In addition to translating when neccesary to Spanish.

I've updated nearly every update in the git tree from my last update, and spread them far and wide, so ideally the lists should be caught up.

I also threw a small update into Chinese, though I think it's probably going to want a more major re-write in the future. It's really behind, the rest of the lists.

### CODE REVIEW

**Comment by SaintFenix** [comment]
Also decided to throw in the fre:ac Audio converter at the last minute, since this would be a good a time as any.

**Comment by LewisVo** [comment]
Awesome work @SaintFenix , I ll take a look to see how great your work is.

**Comment by LewisVo** [comment]
@SaintFenix First of all, I would like to appreciate your work for the community. I have tried all the suggestions, and I like them all, except for that lanmessenger: I can't compile it since I couldn't even get to the qt nokia page. 1 vote for removal of lanmessager

**Comment by SaintFenix** [comment]
No worries, this place has taught me a lot, I hope to give back all I can.

I was able to install the .deb on 17.10 Ubuntu with no issue, however compiling from source proved to be laborious, and unsuccessful. (I do know this is an older program, I used it around 11 years ago, and was shocked it's still getting updated.) Would you prefer that it be source build-able for the other linuxes? Because if so, I'll remove it. :)

**Comment by LewisVo** [comment]
@SaintFenix yeah. Installation alone is not the problem of lanmessenger. If you take a look at its Github Issue page and its Google group, it seems to be a dead project.

**Comment by SaintFenix** [comment]
had a few more changes sitting in the buffer, so I threw those in now, but during that I also removed LANmessenger. I didn't realize that the community was that dead. Shame I really loved using that for years on windows.

**Comment by LewisVo** [comment]
Just review again. Everything looks good. Do you consider removing lanmessenger @SaintFenix ?

**Comment by SaintFenix** [comment]
It is already removed as of my last commit, and from all languages. :)

**Comment by LewisVo** [comment]
@SaintFenix  Actually, you missed something 😄  
image

**Comment by SaintFenix** [comment]
I missed it! I could of sworn I tore that out. Alright, we are go now. 💯

**Pull request merged**
