### PR TITLE
Fix Formatting for Trojita

### PR DESCRIPTION
**Pull request by FussyLux**

### CODE REVIEW

**Comment by LewisVo** [comment]
Hi @FussyLux, thanks for contributing :). I think Qt is a fascinating advantage to be put on the description. What do you think ?

**Comment by FussyLux** [comment]
Sorry, what do you mean by Qt?

**Comment by LewisVo** [comment]
@FussyLux from trojita's home page: 

> Trojitá, a fast Qt IMAP e-mail client. 

I mean this Qt. It is a wellknown framework for developing desktop application.

**Comment by Seanld** [comment]
Qt is a GUI framework. You use it to develop applications with a user
interface. Many programming languages support frameworks for connecting to
Qt and creating frameworks.

**Comment by FussyLux** [comment]
> I mean this Qt. It is a wellknown framework for developing desktop application.

Sorry. I'm not that into Linux as you, I think. I just saw this repo in trending and discovered that little formatting issue.

So you think we should write

>  A fast Qt IMAP e-mail client.

instead of

> A super fast desktop email client for Linux.

**Comment by LewisVo** [comment]
> Sorry. I'm not that into Linux as you, I think. I just saw this repo in trending and discovered that little formatting issue.   

It's totally fine. In fact, Qt is not specific to linux, but it's totally fine that you are not aware of it. It's totally fine. I am just asking for your opinion since you are the one who makes the pull request 😄

**Pull request merged**
