### PR TITLE
Added Sound Switcher Indicator

### PR DESCRIPTION
**Pull request by ijash**
please check audio section.

### CODE REVIEW

**Comment by LewisVo** [comment]
Do you think this is still necessary ? Unity is now no longer maintained and first class citizen of Ubuntu. No other distro seems to use Unity, either.

**Comment by ijash** [comment]
well, i am using it right now, in ubuntu 17.10 and had no issue. Very useful for multiple audio out/ins.. besides, i can't find any of the same software of it's kind. if there is one, i absolutely would like to know.

**Comment by LewisVo** [comment]
@ijash thank you for lettting me know. I am on Ubuntu 17.10 too and I am using this Gnome extension https://extensions.gnome.org/extension/906/sound-output-device-chooser/ . Are you sure your suggestion works with Gnome desktop environment as well? Are you running Unity on 17.10?

**Comment by ijash** [comment]
good to hear an alternative. thanks!
Yes, i am using default gnome DE and got no issues(not unity). make sure to put it on the startup apps.

**Comment by LewisVo** [comment]
> Yes, i am using default gnome DE and got no issues(not unity).  

Then it's a merge

**Pull request merged**
