### PR TITLE
Add Everdo app - cross-platform TODO/GTD app

### PR DESCRIPTION
**Pull request by andreistreltsov**
I've noticed that the list is missing a good desktop GTD (Getting Things Done) app for Linux, and I would like to suggest adding a tool I have build - [Everdo](https://everdo.net).

As a Linux user myself, I know that I would be delighted to find something like this. So I thought it might be a good fit for this list.

It's a productivity app focused on GTD methodology. It's looks good, has great UX and stores data privately on the user's computer (no cloud / SaaS dependency). Linux users might appreciate this. You can learn more about the app [here](https://everdo.net/blog/everdo-mission-values/).

Everdo is packaged for .deb, arch, appimage and rpm, so almost any Linux user can run it easily. It also works on Windows and Mac.

Here's a screenshot
screenshot-for-placeit

### CODE REVIEW

**Comment by LewisVo** [comment]
This is GOLD! Thank you, I did spend the last 4 days with it and it is promising.

**Comment by andreistreltsov** [comment]
Glad you like it! Please let me know if any questions or feedback come up.

On Nov 22, 2017 6:07 PM, "Luong Vo" <notifications@github.com> wrote:

This is GOLD! Thank you, I did spend the last 4 days with it and it is
promising.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LewisVo/Awesome-Linux-Software/pull/306#issuecomment-346377723>,
or mute the thread

**Comment by LewisVo** [comment]
@andreistreltsov If you happens to be its developer, then the only thing I would like to say is good luck. Your app is good, but it's in a category that is a little bit crowded and the top players here did thing really well. I have just signed up on the community forum as Luong Vo. Will post some discussion on their if necessary.

**Comment by andreistreltsov** [comment]
Well, you are right. I'll be happy to just make it a great product. Thanks
for support!

**Pull request merged**
