### PR TITLE
Move icons to left 

### PR DESCRIPTION
**Pull request by ivernus**
Move icons to the left as per #203 and re-check OS/free/paid software, update icons accordingly.

  * Moved icons using regex find/replace in vim
  * Changed some URLs to site pages rather than referrals
  * Manually changed paid/non OS software icons

### CODE REVIEW

**Comment by LewisVo** [comment]
@ivernus Hi there. Thank you for your hard work. I really appreciate it. 
However, there is one problem that I just noticed. Our project has the open source icon linked to the app source page, but now with your moving icon, that kind of link vanished, too. If you are doing all of this via a script, we should modify it a little bit to keep the link that follow the open source icon. 
Does that sound OK to you?

**Comment by ivernus** [comment]
Thanks for reviewing @LewisVo , yep I see those links on the original, I will try to figure out a way of getting them back in.

**Comment by LewisVo** [comment]
@ivernus Thank you so much. Your effort is invaluable. Take your time, and also keep your local updated with upstream since big changes are on the way.

**Comment by ivernus** [comment]
No worries thanks @LewisVo 
Notes on the changes, vim find replace was: 94,941s/\(^-\)\(.*\)\(\[\!\[.*\)/- \3\2/ , plus some manual changes also :disappointed:

**Comment by LewisVo** [comment]
After a thorough review, I can notice some minor problems, like the nonfree icon is still wrapped by brackets. But it's okay. I will continue working on this, you can take a rest now. Thank you

**Comment by LewisVo** [comment]
Done, thanks again @ivernus

**Comment by LewisVo** [comment]
Hi @ivernus , can you make your script or any method that you use to move the icon to the left work with other translation like Spanish

**Comment by ivernus** [comment]
Ill take a look to see how easy it is @LewisVo

**Comment by ivernus** [comment]
Maybe on this one you could do with some sort of i18n documents that could automatically generate the lists to the right format based on some translations? e.g. https://github.com/gisce/markdown-i18n

**Comment by LewisVo** [comment]
That would take some times since I am not familiar with this @ivernus 😄 . Will try do it in my freetime

**Pull request merged**
