### PR TITLE
Adding Advanced Linux Subheader:

### PR DESCRIPTION
**Pull request by SaintFenix**
The Advanced Linux Subheader I feel would give us a place to put more advanced Linux topics, as well as room to grow for people who've been with Linux for awhile, but want to get up to the next level. Right now I've only got Virtual Containers, as well as General Virtualization with Virtualbox as a start.

Many other notable changes include:

Adding three new programs
- Sway Tile Manager
- Knotter
- Zerotier

Reaching equivalency across the languages:
- GNU Octave

Minor Grammar also fixed where found, as well as ordering of one item alphabetically.

pt-BR didn't have a subheading for "other Awesome Lists" so it was added to both the table of contents and to the bottom of the list.

### CODE REVIEW

**Comment by SaintFenix** [comment]
I discovered Zerotier the other evening, and am busy installing it on both of my servers, my phone, and my workstation. It's a game changer for me. So I thought I'd share that love. There is an alternative called Tinc I wanna explore also: https://www.tinc-vpn.org.

But for the now the ease of Zerotier is amazing, and I'm using it a lot already.

**Comment by SaintFenix** [comment]
#305 Saw the fixes for the Albert Links, and also applied them to the other lists, but generally this is just a big grab-bag of keeping the lists equivalent.

**Comment by LewisVo** [comment]
Hi @SaintFenix , sorry for the late reply.
1st of all, thank you for your contribution. You have been one of the most active person on this repo so far.
2nd, it took me a long time to try out each one in the list (especially Sway, I have had a hard time with it since I am not used to i3). All of them is fine, and really helpful. Except for ZeroTierOne. I don't fully understand how it works and how it benefits users. Please shed some light on me.

**Comment by SaintFenix** [comment]
No worries, I've been busy myself, it's currently the holidays here in the United States, so I've been doing a lot. (Holidays in the US usually mean more work, not less. :( )

And no worries, this list taught me Git, and I've been using it a ton since I've learned it. I'm very much enjoying it. :)

Sway took awhile for me too, but I can see that there is a type of person who would love it, I can't say that that person is me, but it's good software.

Zerotier is a program that when installed on a selection of computers turns all of them into a virtual network over the internet. So if I install it on my computer at work, and on my computer at home, to each other they look like they are connected on the same router, so I can SSH into them safely. All these network communications are encrypted, and you can control who can and can't join the Zerotier network you created via a web interface.

Currently I have a few computers at home, and my computer at work, as well as my phone connected. I can use SSH to have them do tasks while I'm at work, or even VNC if I want to look at their desktops. And all I have to do is type in their IP address that they have connected to via Zerotier. I can transfer files (this is limited by the speed of the internet since it is all going over that.) as well as play music from my computers at home.

This is more convenient than opening up ports on a router and possibly leaving you more open to attack, since this doesn't require open ports at all. And it lets you control your computers easily, even via phone. (I can now SSH into my computers from my smartphone, which is really neat.)

I am currently in love with the software and plan on marrying it.

**Comment by LewisVo** [comment]
> I am currently in love with the software and plan on marrying it.   

You will have many wives in the future.

**Pull request merged**
