### PR TITLE
Feature/travis test

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
~~WIP~~

- add awesome bot and awesome lint on travis
- fix most trailing slash
- change headings so that there is no similar content
- not using upper case character in definition label (`oss icon`, `money icon`)
- remove trailing `.` and `?` in headings
- not use emphasis to introduce a section, use a heading
- not use literal url 
- remove unused definition (`chitchat`)
- fix incorrect indentation
- fix incorrect list-item indent
- set marker style to `-`
- add awesome badge after main heading
- set rules to use `---`

todo
- [x] ~~fix error link~~
- [x] ~~fix dupes link~~

known issue 
- [x] `what is ubuntu` is marked as `link-title-style` error (Titles should use `'` as a quote) 

related #196 

e: put all the error and dupe link to white list for now so they can be fixed on another pr.

also change the ubuntu wiki url to use url encoded one to avoid lint error

### CODE REVIEW

**Comment by LewisVo** [comment]
Thank you @rachmadaniHaryono , I will try to review this soon.

**Comment by LewisVo** [comment]
@rachmadaniHaryono  Right now there are a lot of changes coming from others so I ll leave this PR waiting for a while. Thank you for your contribution. Great job.

**Comment by rachmadaniHaryono** [comment]
hi @LewisVo , i'm trying to rebase the pr so it is easier to merge. i will notify you when it is done

**Comment by rachmadaniHaryono** [comment]
it is done @LewisVo

**Comment by LewisVo** [comment]
@rachmadaniHaryono  thank you so much. 
By the way, I and many others may not be familiar with this bot. Can you write a file to briefly introduce how to use it, how to run it .... ?

**Comment by rachmadaniHaryono** [comment]
something like this  (copied from travis config)
```
To run the check locally do the following

$ gem install awesome_bot
$ npm install --global awesome-lint
$ awesome-lint
$ awesome_bot README.md --white-list $(paste -d, -s white_listed_sites.txt)
```
not quite sure if anyone will run it, because it will run automatically from travis for every pr and the result will shown on github.

**Comment by LewisVo** [comment]
Hi @rachmadaniHaryono , I am currently having issues with the build : 
image
Can you suggest me a way to fix this?

**Comment by rachmadaniHaryono** [comment]
For the first link just replace that url to suggested url

For the second one, just add it on white listed text file

**Comment by LewisVo** [comment]
@rachmadaniHaryono  Thank you for the tips. By the way, why is the second one show that it is unreachable?

**Comment by rachmadaniHaryono** [comment]
It depend on the time of of testing and the site itself. Some site can't be tested by bot and some just may output random error due to high request.

**Comment by LewisVo** [comment]
@rachmadaniHaryono I am thinking of reversing this feature. Sorry but it is not worth the effort 😞. After fixing the above 2 errors, other errors came. And these errors seems nonsense to me.

**Comment by rachmadaniHaryono** [comment]
Or you can just disable awesome-bot url check by commenting the line in travis config if it is too much for you

**Comment by LewisVo** [comment]
@rachmadaniHaryono  Beside some semantic cleanup (which also renders the same result), I don't see much benefit in integrating a CI process like this. People are just gonna have a hard time contributing and keeping up with the build status.

**Comment by rachmadaniHaryono** [comment]
OK that is fine

**Pull request merged**
