### PR TITLE
Added Fedora en-EN es-ES pt-BR th-TH

### PR DESCRIPTION
**Pull request by SaintFenix**
Added Fedora to both README, and es-ES, added to pt-BR and th-TH to await translation since the translators haven't yet reached those points.

### CODE REVIEW

**Comment by SaintFenix** [comment]
changing additions, so will close for now.

**Comment by SaintFenix** [comment]
borked and then unborked my branches, so sorry for this looking strange.

Also added cloudtag #287 as per said issue, have translated it appropriately where needed.

**Comment by LewisVo** [comment]
Sorry, I couldn't add Cloudtag into this list. While testing the app, it works just fine. But it is too vague for me to list here. There is no information on how it is built, who built it, what the terms or policies of using it are, etc. Nothing at all. 
It seems fine at first but just imagine you got some problems and have no way or nowhere to address them, which is super terrible. Or more simpler, since they stand as an intermediary between uploader and downloader, they may put some harmful softwares or viruses to the file uploaded blah blah. No one protects you from this, no policy promises you that this won't happen.

**Comment by SaintFenix** [comment]
removed cloudtag

**Comment by LewisVo** [comment]
Thank you @SaintFenix  👍

**Pull request merged**
