### PR TITLE
Moving Icons to the Left: README_es-ES

### PR DESCRIPTION
**Pull request by SaintFenix**
Adjusted Spanish to follow the new formatting, also as always smaller grammar was corrected in the English version where noticed.

Also additional software from English has been added to Spanish.

### CODE REVIEW

**Comment by LewisVo** [comment]
Impressive! How did you achieve this? Please don't tell me you do all this manually 😆

**Comment by SaintFenix** [comment]
I did all this manually. 😢 But thankfully it's a one time deal.

I couldn't find enough notepad++ search fu to do it any easier.

**Comment by LewisVo** [comment]
Switch to another editor. I dont want to be offensive but Notepad++ is too old 😆. Also, learn Regex, it would make your life better 👍 @SaintFenix

**Comment by SaintFenix** [comment]
I actually use atom, but am more familiar with Notepad++'s search. I'll give regex a look. 👍

**Comment by ranguli** [comment]
There's a lot more power in a modal editor if you wanted to give one of those a try :^)

**Pull request merged**
