### PR TITLE
Added ReadyMedia and Streaming subcategory

### PR DESCRIPTION
**Pull request by davamigo**
Created Streaming subcategory inside Applications/Graphics
Added ReadyMedia (formerly known as MiniDLNA)

### CODE REVIEW

**Comment by LewisVo** [comment]
thank you @davamigo  for coming back with another software. this one took me a bunch of runtime to know it well. I don't know sourceforge well but depending on the project's Github page here https://github.com/azatoth/minidlna it seems that development has been stopped. Well maybe it is still stable and working fine but would you mind enlighten me on why we should choose readymedia instead of something like Kodi?

**Comment by davamigo** [comment]
I have been using this software for 5 years in a very old PC with Ubuntu 12.04 as my personal DLNA server. I like it because it's really lightweight and very easy to configure. I think the Github page is not the oficial one. The last release in Sourceforge is from 2017-08-24 (https://sourceforge.net/projects/minidlna/files/minidlna/). I don't think development is stopped.

**Comment by LewisVo** [comment]
Thank you @davamigo 😄

**Comment by davamigo** [comment]
Of course I don't mind. I think you project is a very good idea and you're doing a very good job filtering and categorizing the apps.

I put it in a different subcategory because it's not actually a video player, but a media streamer (for video, audio and images). A DLNA or UPnP compatible media player is needed to be useful. But if you think another category is better, you should move it. :)

**Pull request merged**
