### PR TITLE
Added Encryptr to security and vokoscreen to utilities

### PR DESCRIPTION
**Pull request by rajula96reddy**

### CODE REVIEW

**Comment by LewisVo** [comment]
Hey there, thank you for your contribution. I need sometimes to test your suggestions 🏷 . Until then can you keep the list sorted with your pull request ?

**Comment by rajula96reddy** [comment]
Hi! Yeah sure! I will keep the list unchanged.

**Comment by LewisVo** [comment]
@rajula96reddy  I mean, your pull request is not alphabetically sorted. Can you fix that?

**Comment by rajula96reddy** [comment]
@LewisVo Sorry. I get it! Let me fix it.

**Comment by LewisVo** [comment]
Two softwares working beautifully. Thank you so much.

**Comment by rajula96reddy** [comment]
My pleasure. Thanks for merging. BTW Great collection! I will see if I can add any more.

**Comment by LewisVo** [comment]
@rajula96reddy  thank you. I am glad to see it helps more people ;)

**Pull request merged**
