### PR TITLE
Spanish Translation finished ES

### PR DESCRIPTION
**Pull request by SaintFenix**
Fixed more grammar on the English side while I was at it, but the Spanish translation is now complete.

The only remaining tasks will be to keep it up to date, and ask for the wider world to help with the Spanish in the list, since it's not my native language, and it has many technical terms I've not used much.

### CODE REVIEW

**Comment by SaintFenix** [comment]
nevermind will resubmit without conflicts.

**Comment by SaintFenix** [comment]
Lets try this again.

**Comment by SaintFenix** [comment]
Decided to add one more commit for the asort.py README. It now also has a Spanish section.

**Comment by LewisVo** [comment]
Hi @SaintFenix , try to think carefully before making pull requests. We are neither in no rush or have any deadlines to meet.  Conflicts are mostly caused because your branch is not updated with master upstream (because when you are working on your own, someone is working and get merged here). 
Github also notifies that to you when you open a pull request (it shows a message like : cannot merge directly or something, i dont remember). 
Take a look into this : https://ginsys.eu/git-and-github-keeping-a-feature-branch-updated-with-upstream/
Nothing serious. Just tips for you/

**Comment by SaintFenix** [comment]
It was good actually that it happened, because I then had to learn how to deal with a conflict. You were correct, it was my branch not keeping up with the master, a quick revert and re-implementing the changes fixed it. 

And I'm in no particular hurry, I've been working on this in my spare-time. The only reason I've been around so much is because I'm really into learning Git, and I've learned a ton by contributing here. It'll slow down now, there isn't much more I can contribute. The list is looking great.

And thanks for the article, I'll give it a read through.

**Comment by LewisVo** [comment]
@SaintFenix  and join this also : https://hacktoberfest.digitalocean.com/ It's a great event this October

**Comment by SaintFenix** [comment]
I'll give it a look, I've heard the word before, never actually looked into it though.

**Pull request merged**
