### PR TITLE
Add llpp as PDF and ePub reader

### PR DESCRIPTION
**Pull request by onlurking**

### CODE REVIEW

**Comment by LewisVo** [comment]
It would be nice if you put llpp before lucidor. Other than that, all is great. I have tried this. Jesus, I never thought of the day when they put Vim navigating in my pdf viewer

**Comment by onlurking** [comment]
Is even better when you change `background-color='128/128/128'` to `background-color='255/255/255'` on `~/.config/llpp.conf`, and use <kbd>f</kbd> to fullscreen and <kbd>b</kbd> to hide the scrollbar, and voalá, the best minimalist and distraction free pdf/epub reader ever made. 🎉 

Btw, I will place llpp before lucidor, thanks.

**Comment by onlurking** [comment]
@LewisVo done.

**Comment by LewisVo** [comment]
Thank you @onlurking

**Pull request merged**
