### PR TITLE
[Albert] Fix links, generalize description

### PR DESCRIPTION
**Pull request by ManuelSchneid3r**

### CODE REVIEW

**Comment by SaintFenix** [comment]
In my pull request, I have applied this fix to the other lists not listed here.

**Comment by ManuelSchneid3r** [comment]
@SaintFenix okay thats cool, but could you also appy the generalization? Albert is not only an app launcher

**Comment by SaintFenix** [comment]
The thing about that is I only maintain perfectly is the [Spanish one](https://github.com/LewisVo/Awesome-Linux-Software/blob/master/README_es-ES.md) in full translation, and in the Spanish translation I've got the following: 

`- [![Open-Source Software][OSS Icon]](https://github.com/albertlauncher/albert) [Albert](https://github.com/albertlauncher/albert) - Un lanzador de aplicaciones muy capaz para Linux.`

English is a very specific language, and often-times leaves very little room for interpretation with its many many adjectives, Whereas Spanish while it too has adjectives tends to leave the subtlety to the situation. So it was already very generally written.

The description translated above literally means: "An application launcher that is very capable, for linux." in this sense, application not being the typical computer definition of program, but any number of practical applications. So it was already implied.

The remainder of the lists are easy. They haven't fully been translated yet, so I add them in the areas that aren't already translated, just so when someone gets to them, they will already have them on that list to be translated.

**Comment by LewisVo** [comment]
Thank you @ManuelSchneid3r  and @SaintFenix

**Pull request merged**
