### PR TITLE
Added FireHOL and netdata tools

### PR DESCRIPTION
**Pull request by ktsaou**
firehol.org tools for Linux

1. firehol
2. fireqos
3. iprange
4. update-ipsets
5. netdata

### CODE REVIEW

**Comment by LewisVo** [comment]
Hi @ktsaou, thank you for your pull request. Please give me some times to try these out. Until then, let's leave this open. 🏁

**Comment by ktsaou** [comment]
of course, take your time.

I hope you will like them...

**Comment by LewisVo** [comment]
@ktsaou it's not that I like them or not. This list is not about preference. But I have to run them to see whether they work, whether they are safe to use, still maintained , .etc

**Comment by ktsaou** [comment]
oh dear... this is an easy answer then...

**Comment by LewisVo** [comment]
HI @ktsaou, all your suggestions are working fine 👍 . However, some items are not alphabetically sorted. For example, FireHOL should be above FireQOS and iprange should lie before OpenSSH. Also, I think it would be better to keep the first letter of all items capitalized. It would be great if you could fix these minor issues  ❤️

**Comment by LewisVo** [comment]
Thank you so much @ktsaou , have a nice day 🍺

**Pull request merged**
