### PR TITLE
Starting the translation to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by cogumm**
Hi,
I would like to begin the translation to Brazilian Portuguese of this wonderful project.

Thank you very much man!

### CODE REVIEW

**Comment by LewisVo** [comment]
WOW!! This is really cool! Thank you so much. Thank you. Your translation is helping Linux software reach more audiences. Keep up the good work. Do you want me to leave this open until you feel it's the right time to merge or merge now ?

**Comment by cogumm** [comment]
You can already do the merge please, i'm already working without a main file, sory.
[README_pt-BR](https://github.com/cogumm/Awesome-Linux-Software/blob/master/README_pt-BR.md)

**Comment by LewisVo** [comment]
@cogumm you should wait one more day before continuing your work. I am working on some changes that may heavily affect the repo.

**Comment by cogumm** [comment]
Okay man!

**Pull request merged**
