### PR TITLE
Add Dino in Chat clients

### PR DESCRIPTION
**Pull request by uchchishta**
Include [Dino](https://github.com/dino/dino)

### CODE REVIEW

**Comment by LewisVo** [comment]
Thank you for your contribution. It would take me some time to try this out. Currently, I cant run in on my machine. Will test on another machine and recheck ;)

**Comment by uchchishta** [comment]
Sure ;) for convenience here are some [distro packages ](https://github.com/dino/dino/wiki/Distribution-Packages)

**Comment by LewisVo** [comment]
It's a pity that there is no package available for Ubuntu/ Debian. But it is still rocking on my Fedora so merging is on the way 👍

**Comment by uchchishta** [comment]
Thanks :) Debian package will arrive soon

**Pull request merged**
