### PR TITLE
Created A partial Spanish Translation:

### PR DESCRIPTION
**Pull request by SaintFenix**
I've been working on this on and off for the past few days, thought we could open it for more participation, but I've created a Spanish translation of the list, and will continue work until it's done. Then the task of maintaining parity will begin.

I wonder if there is an easier way to do this, I was working on it in a branch for just a day, and it there was lot of drift.

Also noteworthy, I did a lot of grammar checks on the English list as well because translating to Spanish highlights very well where some of the English errs. So edits were done frequently on both, often at the same time.

I decided now was good enough to push it, since it's reached parity with the Brazilian Portuguese copy.

### CODE REVIEW

**Comment by SaintFenix** [comment]
This has come quite a ways since the post went up. I've fixed a lot of grammar on the English side, and am continuing the translation into Spanish. 

I've also edited the Portuguese version where it's not in Portuguese to reflect new programs added to the list.

There are tons and tons of grammar corrections in the English list, as well as small re-orderings.

**Comment by LewisVo** [comment]
@SaintFenix I haven't reviewed this yet, but you should try to work on fewer commits. Think ahead what to change carefully, and combine as many changes as possible into one commit. In real project, the more mini commits you have, the harder for you to revert if something goes wrong as you spam the history of the branch.

**Comment by SaintFenix** [comment]
Oh okay, I can do that. I didn't realize that would be an issue, but that makes sense.

**Comment by LewisVo** [comment]
@SaintFenix It is recommended to commit often to keep your work safe. Commit serves us like checkpoints int game. But try not to spam the log with commit messages when you are ready to push. 
Pro tips: There are many methods to achieve this. 
Look for how to use `git commit --amend --no-edit` or `git rebase -i master` with `pick` and `squash`or simply commit as many as you like, then reset to the first state then commit again in one (this method is called commit first, perfect later)

**Comment by SaintFenix** [comment]
Okay, I can do that, I'm using Gitkraken, and I'm learning how this all works as I do it. It's a lot of fun actually, but I'm still learning the norms. Sorry to spam so many. I can figure out those commands and do those from here on out. 

You have very good advice, I'm following every bit you give me. 💯

**Comment by LewisVo** [comment]
@SaintFenix  dont worry. It's totally fine. I mark the issue that this is "beginner-friendly" so I will help beginners, not roast them. 😄 Just make sure you follow the best practice in a bigger projects. This repo is not that serious.
I don't use GitKraken, but it should have a GUI-way to achieve the same thing as my commands.

**Pull request merged**
